"""add_file_activities_table

Revision ID: 251b7ae30744
Revises: 9f45be8d2b0e
Create Date: 2026-08-02 08:17:42.208249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '251b7ae30744'
down_revision: Union[str, Sequence[str], None] = '9f45be8d2b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('plan_item_id', sa.String(length=36), nullable=True),
    sa.Column('agent_id', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=2000), nullable=False),
    sa.Column('normalized_path', sa.String(length=2000), nullable=False),
    sa.Column('tree_identity', sa.String(length=2000), nullable=False),
    sa.Column('repository_path', sa.String(length=1000), nullable=False),
    sa.Column('worktree_path', sa.String(length=1000), nullable=True),
    sa.Column('attribution_type', sa.String(length=30), nullable=False),
    sa.Column('attribution_confidence', sa.Float(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_item_id'], ['plan_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_file_activities_attribution_type', 'file_activities', ['attribution_type'], unique=False)
    op.create_index('ix_file_activities_event_type', 'file_activities', ['event_type'], unique=False)
    op.create_index('ix_file_activities_normalized_path', 'file_activities', ['normalized_path'], unique=False)
    op.create_index('ix_file_activities_occurred_at', 'file_activities', ['occurred_at'], unique=False)
    op.create_index('ix_file_activities_project_id', 'file_activities', ['project_id'], unique=False)
    op.create_index('ix_file_activities_session_id', 'file_activities', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_file_activities_session_id', table_name='file_activities')
    op.drop_index('ix_file_activities_project_id', table_name='file_activities')
    op.drop_index('ix_file_activities_occurred_at', table_name='file_activities')
    op.drop_index('ix_file_activities_normalized_path', table_name='file_activities')
    op.drop_index('ix_file_activities_event_type', table_name='file_activities')
    op.drop_index('ix_file_activities_attribution_type', table_name='file_activities')
    op.drop_table('file_activities')
    # ### end Alembic commands ###
