"""add_verdict_audit_json

Revision ID: 41d57a685feb
Revises: 251b7ae30744
Create Date: 2026-08-02 09:08:59.771183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41d57a685feb'
down_revision: Union[str, Sequence[str], None] = '251b7ae30744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_reports', sa.Column('verdict_audit_json', sa.Text(), nullable=True))
    op.add_column('agent_sessions', sa.Column('result_commit_sha', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_sessions', 'result_commit_sha')
    op.drop_column('agent_reports', 'verdict_audit_json')
    # ### end Alembic commands ###
