"""plan_model_tables

Revision ID: 6aca1fa7366b
Revises: 03de14cbf6aa
Create Date: 2026-07-31 18:15:28.145444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aca1fa7366b'
down_revision: Union[str, Sequence[str], None] = '03de14cbf6aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('repo_path', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_status', 'projects', ['status'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plans_project_id', 'plans', ['project_id'], unique=False)
    op.create_table('plan_phases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('phase_key', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'phase_key', name='uq_plan_phases_key')
    )
    op.create_index('ix_plan_phases_plan_id', 'plan_phases', ['plan_id'], unique=False)
    op.create_table('plan_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_phase_id', sa.String(length=36), nullable=False),
    sa.Column('item_key', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_source', sa.String(length=20), nullable=False),
    sa.Column('owner_session_id', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('implemented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_phase_id'], ['plan_phases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plan_items_item_key', 'plan_items', ['item_key'], unique=False)
    op.create_index('ix_plan_items_phase_id', 'plan_items', ['plan_phase_id'], unique=False)
    op.create_index('ix_plan_items_status', 'plan_items', ['status'], unique=False)
    op.create_table('plan_item_criteria',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_item_id', sa.String(length=36), nullable=False),
    sa.Column('criterion_key', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('evidence_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('verification_summary', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_item_id'], ['plan_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plan_item_criteria_item_id', 'plan_item_criteria', ['plan_item_id'], unique=False)
    op.create_index('ix_plan_item_criteria_status', 'plan_item_criteria', ['status'], unique=False)
    op.create_table('plan_item_dependencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_item_id', sa.String(length=36), nullable=False),
    sa.Column('depends_on_plan_item_id', sa.String(length=36), nullable=False),
    sa.Column('dependency_type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_plan_item_id'], ['plan_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_item_id'], ['plan_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_item_id', 'depends_on_plan_item_id', name='uq_dependency_pair')
    )
    op.create_index('ix_deps_depends_on', 'plan_item_dependencies', ['depends_on_plan_item_id'], unique=False)
    op.create_index('ix_deps_plan_item_id', 'plan_item_dependencies', ['plan_item_id'], unique=False)
    op.create_table('plan_progress_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_item_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('agent_report_id', sa.String(length=36), nullable=True),
    sa.Column('from_status', sa.String(length=20), nullable=False),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('evidence_artifact_ids_json', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_item_id'], ['plan_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_progress_events_item_id', 'plan_progress_events', ['plan_item_id'], unique=False)
    op.create_index('ix_progress_events_occurred_at', 'plan_progress_events', ['occurred_at'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('plan_item_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['plan_item_id'], ['plan_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_priority', 'tasks', ['priority'], unique=False)
    op.create_index('ix_tasks_project_id', 'tasks', ['project_id'], unique=False)
    op.create_index('ix_tasks_status', 'tasks', ['status'], unique=False)
    op.create_table('agent_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=True),
    sa.Column('execution_mode', sa.String(length=30), nullable=False),
    sa.Column('terminal_label', sa.String(length=100), nullable=True),
    sa.Column('working_directory', sa.String(length=1000), nullable=True),
    sa.Column('repo_path', sa.String(length=1000), nullable=False),
    sa.Column('branch_name', sa.String(length=500), nullable=True),
    sa.Column('worktree_path', sa.String(length=1000), nullable=True),
    sa.Column('base_commit_sha', sa.String(length=40), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('plan_item_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['plan_item_id'], ['plan_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_sessions_execution_mode', 'agent_sessions', ['execution_mode'], unique=False)
    op.create_index('ix_agent_sessions_project_id', 'agent_sessions', ['project_id'], unique=False)
    op.create_index('ix_agent_sessions_status', 'agent_sessions', ['status'], unique=False)
    op.create_index('ix_agent_sessions_task_id', 'agent_sessions', ['task_id'], unique=False)
    op.create_table('session_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_session_events_event_type', 'session_events', ['event_type'], unique=False)
    op.create_index('ix_session_events_occurred_at', 'session_events', ['occurred_at'], unique=False)
    op.create_index('ix_session_events_session_id', 'session_events', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_events_session_id', table_name='session_events')
    op.drop_index('ix_session_events_occurred_at', table_name='session_events')
    op.drop_index('ix_session_events_event_type', table_name='session_events')
    op.drop_table('session_events')
    op.drop_index('ix_agent_sessions_task_id', table_name='agent_sessions')
    op.drop_index('ix_agent_sessions_status', table_name='agent_sessions')
    op.drop_index('ix_agent_sessions_project_id', table_name='agent_sessions')
    op.drop_index('ix_agent_sessions_execution_mode', table_name='agent_sessions')
    op.drop_table('agent_sessions')
    op.drop_index('ix_tasks_status', table_name='tasks')
    op.drop_index('ix_tasks_project_id', table_name='tasks')
    op.drop_index('ix_tasks_priority', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_progress_events_occurred_at', table_name='plan_progress_events')
    op.drop_index('ix_progress_events_item_id', table_name='plan_progress_events')
    op.drop_table('plan_progress_events')
    op.drop_index('ix_deps_plan_item_id', table_name='plan_item_dependencies')
    op.drop_index('ix_deps_depends_on', table_name='plan_item_dependencies')
    op.drop_table('plan_item_dependencies')
    op.drop_index('ix_plan_item_criteria_status', table_name='plan_item_criteria')
    op.drop_index('ix_plan_item_criteria_item_id', table_name='plan_item_criteria')
    op.drop_table('plan_item_criteria')
    op.drop_index('ix_plan_items_status', table_name='plan_items')
    op.drop_index('ix_plan_items_phase_id', table_name='plan_items')
    op.drop_index('ix_plan_items_item_key', table_name='plan_items')
    op.drop_table('plan_items')
    op.drop_index('ix_plan_phases_plan_id', table_name='plan_phases')
    op.drop_table('plan_phases')
    op.drop_index('ix_plans_project_id', table_name='plans')
    op.drop_table('plans')
    op.drop_index('ix_projects_status', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
