"""add_phase3_tables

Revision ID: 96aa6257d45c
Revises: d62470d60bc8
Create Date: 2026-08-02 21:49:20.366919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96aa6257d45c'
down_revision: Union[str, Sequence[str], None] = 'd62470d60bc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conflicts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=2000), nullable=False),
    sa.Column('session_ids_json', sa.Text(), nullable=False),
    sa.Column('conflict_level', sa.String(length=10), nullable=False),
    sa.Column('conflict_key', sa.String(length=128), nullable=True),
    sa.Column('conflict_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False, server_default='1'),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conflicts_detected_at', 'conflicts', ['detected_at'], unique=False)
    op.create_index('ix_conflicts_level', 'conflicts', ['conflict_level'], unique=False)
    op.create_index('ix_conflicts_project_id', 'conflicts', ['project_id'], unique=False)
    op.create_index('ix_conflicts_status', 'conflicts', ['status'], unique=False)
    op.create_index('ix_conflicts_conflict_key', 'conflicts', ['conflict_key'], unique=True)
    op.create_table('agent_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('agent_job_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('impact_summary', sa.Text(), nullable=True),
    sa.Column('reproduction_summary', sa.Text(), nullable=True),
    sa.Column('context_used', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('implementation_summary', sa.Text(), nullable=True),
    sa.Column('untouched_scope', sa.Text(), nullable=True),
    sa.Column('verification_summary', sa.Text(), nullable=True),
    sa.Column('independent_review_summary', sa.Text(), nullable=True),
    sa.Column('found_issues', sa.Text(), nullable=True),
    sa.Column('rejected_options', sa.Text(), nullable=True),
    sa.Column('conflicting_sources', sa.Text(), nullable=True),
    sa.Column('commit_shas_json', sa.Text(), nullable=True),
    sa.Column('changed_files_json', sa.Text(), nullable=True),
    sa.Column('open_risks', sa.Text(), nullable=True),
    sa.Column('follow_up', sa.Text(), nullable=True),
    sa.Column('user_confirmation_required', sa.Boolean(), nullable=False),
    sa.Column('user_verdict', sa.String(length=20), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('verdict_audit_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_reports_session_id', 'agent_reports', ['session_id'], unique=False)
    op.create_index('ix_agent_reports_status', 'agent_reports', ['status'], unique=False)
    op.create_table('file_activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('plan_item_id', sa.String(length=36), nullable=True),
    sa.Column('agent_id', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=2000), nullable=False),
    sa.Column('normalized_path', sa.String(length=2000), nullable=False),
    sa.Column('tree_identity', sa.String(length=2000), nullable=False),
    sa.Column('repository_path', sa.String(length=1000), nullable=False),
    sa.Column('worktree_path', sa.String(length=1000), nullable=True),
    sa.Column('attribution_type', sa.String(length=30), nullable=False),
    sa.Column('attribution_confidence', sa.Float(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_item_id'], ['plan_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_file_activities_attribution_type', 'file_activities', ['attribution_type'], unique=False)
    op.create_index('ix_file_activities_event_type', 'file_activities', ['event_type'], unique=False)
    op.create_index('ix_file_activities_normalized_path', 'file_activities', ['normalized_path'], unique=False)
    op.create_index('ix_file_activities_occurred_at', 'file_activities', ['occurred_at'], unique=False)
    op.create_index('ix_file_activities_project_id', 'file_activities', ['project_id'], unique=False)
    op.create_index('ix_file_activities_session_id', 'file_activities', ['session_id'], unique=False)
    op.add_column('agent_sessions', sa.Column('result_commit_sha', sa.String(length=40), nullable=True))
    op.add_column('agent_sessions', sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_sessions', 'last_heartbeat_at')
    op.drop_column('agent_sessions', 'result_commit_sha')
    op.drop_index('ix_file_activities_session_id', table_name='file_activities')
    op.drop_index('ix_file_activities_project_id', table_name='file_activities')
    op.drop_index('ix_file_activities_occurred_at', table_name='file_activities')
    op.drop_index('ix_file_activities_normalized_path', table_name='file_activities')
    op.drop_index('ix_file_activities_event_type', table_name='file_activities')
    op.drop_index('ix_file_activities_attribution_type', table_name='file_activities')
    op.drop_table('file_activities')
    op.drop_index('ix_agent_reports_status', table_name='agent_reports')
    op.drop_index('ix_agent_reports_session_id', table_name='agent_reports')
    op.drop_table('agent_reports')
    op.drop_index('ix_conflicts_conflict_key', table_name='conflicts')
    op.drop_index('ix_conflicts_status', table_name='conflicts')
    op.drop_index('ix_conflicts_project_id', table_name='conflicts')
    op.drop_index('ix_conflicts_level', table_name='conflicts')
    op.drop_index('ix_conflicts_detected_at', table_name='conflicts')
    op.drop_table('conflicts')
    # ### end Alembic commands ###
