"""resume_models

Revision ID: 41009440b28e
Revises: 6aca1fa7366b
Create Date: 2026-08-01 06:30:10.753824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41009440b28e'
down_revision: Union[str, Sequence[str], None] = '6aca1fa7366b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('plan_item_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('commit_shas_json', sa.Text(), nullable=True),
    sa.Column('changed_files_json', sa.Text(), nullable=True),
    sa.Column('attribution', sa.String(length=30), nullable=False),
    sa.Column('user_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ext_activity_project_id', 'external_activities', ['project_id'], unique=False)
    op.create_table('project_reconciliation_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('previous_commit_sha', sa.String(length=40), nullable=True),
    sa.Column('current_commit_sha', sa.String(length=40), nullable=True),
    sa.Column('previous_branch', sa.String(length=500), nullable=True),
    sa.Column('current_branch', sa.String(length=500), nullable=True),
    sa.Column('previous_dirty_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('current_dirty_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('result', sa.String(length=30), nullable=False),
    sa.Column('new_commit_shas_json', sa.Text(), nullable=True),
    sa.Column('changed_files_json', sa.Text(), nullable=True),
    sa.Column('user_resolution', sa.String(length=30), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rec_events_occurred_at', 'project_reconciliation_events', ['occurred_at'], unique=False)
    op.create_index('ix_rec_events_project_id', 'project_reconciliation_events', ['project_id'], unique=False)
    op.create_table('project_resume_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('active_plan_id', sa.String(length=36), nullable=True),
    sa.Column('last_plan_item_id', sa.String(length=36), nullable=True),
    sa.Column('last_task_id', sa.String(length=36), nullable=True),
    sa.Column('last_session_id', sa.String(length=36), nullable=True),
    sa.Column('last_report_id', sa.String(length=36), nullable=True),
    sa.Column('last_commit_sha', sa.String(length=40), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resume_status', sa.String(length=30), nullable=False),
    sa.Column('where_stopped', sa.Text(), nullable=True),
    sa.Column('next_concrete_step', sa.Text(), nullable=True),
    sa.Column('resume_preconditions', sa.Text(), nullable=True),
    sa.Column('open_blockers_json', sa.Text(), nullable=True),
    sa.Column('open_decisions_json', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index('ix_rs_project_id', 'project_resume_states', ['project_id'], unique=False)
    op.create_table('project_workspace_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('last_known_commit_sha', sa.String(length=40), nullable=True),
    sa.Column('last_known_branch', sa.String(length=500), nullable=True),
    sa.Column('last_known_status_porcelain', sa.Text(), nullable=True),
    sa.Column('last_known_dirty_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('last_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reconciliation_status', sa.String(length=30), nullable=False),
    sa.Column('external_change_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index('ix_ws_project_id', 'project_workspace_states', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ws_project_id', table_name='project_workspace_states')
    op.drop_table('project_workspace_states')
    op.drop_index('ix_rs_project_id', table_name='project_resume_states')
    op.drop_table('project_resume_states')
    op.drop_index('ix_rec_events_project_id', table_name='project_reconciliation_events')
    op.drop_index('ix_rec_events_occurred_at', table_name='project_reconciliation_events')
    op.drop_table('project_reconciliation_events')
    op.drop_index('ix_ext_activity_project_id', table_name='external_activities')
    op.drop_table('external_activities')
    # ### end Alembic commands ###
