"""Standardni kodovi API grešaka."""

from enum import StrEnum


class ErrorCode(StrEnum):
    # Sistemske
    INTERNAL_ERROR = "INTERNAL_ERROR"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"

    # Validacija
    VALIDATION_ERROR = "VALIDATION_ERROR"

    # Resursi
    PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
    TASK_NOT_FOUND = "TASK_NOT_FOUND"
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    CONFLICT_NOT_FOUND = "CONFLICT_NOT_FOUND"
    REPORT_NOT_FOUND = "REPORT_NOT_FOUND"
    ARTIFACT_NOT_FOUND = "ARTIFACT_NOT_FOUND"
    JOB_NOT_FOUND = "JOB_NOT_FOUND"

    # Konflikti / stanje
    SESSION_ALREADY_ENDED = "SESSION_ALREADY_ENDED"
    DUPLICATE_EVENT = "DUPLICATE_EVENT"
    WORKTREE_IN_USE = "WORKTREE_IN_USE"
    GIT_ERROR = "GIT_ERROR"

    # Kontrola
    NOT_MANAGED_MODE = "NOT_MANAGED_MODE"
    CANNOT_CANCEL = "CANNOT_CANCEL"
