"""Tipovi događaja sesije."""

from enum import StrEnum


class EventType(StrEnum):
    STARTED = "STARTED"
    GIT_SNAPSHOT = "GIT_SNAPSHOT"
    COMMIT_OBSERVED = "COMMIT_OBSERVED"
    FILE_ACTIVITY = "FILE_ACTIVITY"
    CONFLICT_WARNING = "CONFLICT_WARNING"
    VERIFY_RESULT = "VERIFY_RESULT"
    CHECKPOINT = "CHECKPOINT"
    NOTE = "NOTE"
    COMPLETED = "COMPLETED"
    ABANDONED = "ABANDONED"
